<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1511420975237" stop="1511420984743">
    <name>Default Suite</name>
    <test-cases>
        <test-case start="1511420980768" stop="1511420984275" status="failed">
            <name>deleteUser</name>
            <title>Удалить пользователя</title>
            <failure>
                <message>AssertionError: expected [8] but found [9]</message>
                <stack-trace>java.lang.AssertionError: expected [8] but found [9]
                    at org.testng.Assert.fail(Assert.java:93)
                    at org.testng.Assert.failNotEquals(Assert.java:512)
                    at org.testng.Assert.assertEqualsImpl(Assert.java:134)
                    at org.testng.Assert.assertEquals(Assert.java:115)
                    at org.testng.Assert.assertEquals(Assert.java:388)
                    at org.testng.Assert.assertEquals(Assert.java:398)
                    at Users.DeleteUser.deleteUser(DeleteUser.java:36)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:498)
                    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
                    at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
                    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
                    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
                    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
                    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
                    at org.testng.TestRunner.privateRun(TestRunner.java:744)
                    at org.testng.TestRunner.run(TestRunner.java:602)
                    at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
                    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
                    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
                    at org.testng.SuiteRunner.run(SuiteRunner.java:289)
                    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
                    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
                    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
                    at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
                    at org.testng.TestNG.runSuites(TestNG.java:1144)
                    at org.testng.TestNG.run(TestNG.java:1115)
                    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
                    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
                </stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
